<br>

# RAJs, Circunscrição Judiciária e Comarcas

Por meio do _site_ [Quem Somos](https://www.tjsp.jus.br/QuemSomos/QuemSomos/RegioesAdministrativasJudiciarias) obtenho as informações das _Regiões Administrativas Judiciárias_.

In [15]:
from tjsp_unidades import pagina
from tjsp_unidades.paths import output_path_tab

In [16]:
quem_somos = pagina.QuemSomos()

<br>

---

## RAJs

Pego os dados das RAJs

In [17]:
df_raj = quem_somos.rajs

df_raj.head()

,id_raj,raj_nome,raj_sigla,raj_regiao,juiz_diretor_nome,juiz_diretor_email
0,1,1ª RAJ - Grande São Paulo,1ª RAJ,Grande São Paulo,Fernando Antonio Tasso,daraj1@tjsp.jus.br
1,2,2ª RAJ - Araçatuba,2ª RAJ,Araçatuba,Antonio Fernando Sanches Batagelo,daraj2@tjsp.jus.br
2,3,3ª RAJ - Bauru,3ª RAJ,Bauru,Gilmar Ferraz Garmes,daraj3@tjsp.jus.br
3,4,4ª RAJ - Campinas,4ª RAJ,Campinas,Nelson Augusto Bernardes de Souza,daraj4@tjsp.jus.br
4,5,5ª RAJ - Presidente Prudente,5ª RAJ,Presidente Prudente,José Wagner Parrão Molina,daraj5@tjsp.jus.br

In [18]:
filename = "RAJs"

df_raj.to_csv(
    path_or_buf=output_path_tab / f"{filename}.csv",
    index=False,
)

df_raj.to_excel(
    excel_writer=output_path_tab / f"{filename}.xlsx",
    index=False,
    sheet_name=f"{filename}",
)

<br>

---

## Circunscrições Judiciárias (CJs)

Obtenhos também os dados de _Circunscrições Judiciárias_.

In [19]:
df_cj = quem_somos.cjs

df_cj.head()

   id_cj cj_sigla                      cj_nome  id_raj
0      0  Capital                      Capital       1
1      1    1ª CJ  1ª Circunscrição Judiciária       7
2      2    2ª CJ  2ª Circunscrição Judiciária       1
3      3    3ª CJ  3ª Circunscrição Judiciária       1
4      4    4ª CJ  4ª Circunscrição Judiciária       1

In [20]:
filename = 'Circunscrições Judiciárias'

df_cj.to_csv(
    path_or_buf=output_path_tab / f'{filename}.csv',
    index=False,
)

df_cj.to_excel(
    excel_writer=output_path_tab / f'{filename}.xlsx',
    sheet_name=f'{filename}',
    index=False,
)

<br>

---

## Comarcas

Por fim, obtemos a lista de Comarcas por CJ.

In [21]:
df_comarca = quem_somos.comarcas

df_comarca.head()

São 321 comarcas

  comarca_tjsp  id_cj
0   Adamantina     30
1        Aguaí     50
2       Agudos     32
3  Altinópolis     39
4    Americana     53

In [22]:
filename = "Comarcas e CJs"

df_comarca.to_csv(
    path_or_buf=output_path_tab / f"{filename}.csv",
    index=False,
)

df_comarca.to_excel(
    excel_writer=output_path_tab / f"{filename}.xlsx",
    index=False,
    sheet_name=f"{filename}",
)