<br>

# Municípios e Comarcas

Por meio do _site_ [ListaTelefonica](https://www.tjsp.jus.br/ListaTelefonica) foi possível relevar as APIs que operam e fazer diversas pesquisas.

<br>

Michel Metran\
Data: 18.06.2024\
Atualizado em: 18.06.2024

In [1]:
import pandas as pd

from tjsp_unidades import extract
from tjsp_unidades.paths import output_path_tab
from tjsp_unidades.transform.small_functions import adjust_columns

<br>

---

## Lista de Unidades

Uma vez com a lista de todos os municípios e seus respectivos códigos, foi possível obter as informações dos fóruns por meio de outro método `POST`.

In [2]:
listar_unidades = extract.ListarUnidades()

In [3]:
# Apenas Exemplo da Função!
listar_unidades.get_unidades(id_municipio_tjsp=6504)

,id_municipio_tjsp,raj,municipio_tjsp,comarca_tjsp,comarca_sede,unidades
0,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum I Adamantina
1,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum II Adamantina (Residência Oficial)
2,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum III Adamantina - UAAJ - FAC. ADAM. INTEG...

<br>

Uma vez com a função que obter os dados das Unidades e, PRINCIPALMENTE, obter as comarcas!
Foi possível iterar pelos 645 municípios para pegar as informações!

In [4]:
# Read Data
df_municipios = pd.read_csv(
    filepath_or_buffer=output_path_tab / "Municipios.csv",
)

# Results
df_municipios.info()
df_municipios.head()

<class 'pandas.DataFrame'>
RangeIndex: 645 entries, 0 to 644
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_municipio_ibge         645 non-null    int64
 1   id_municipio_tjsp         645 non-null    int64
 2   municipio_tjsp            645 non-null    str
 3   municipio_tjsp_corrigido  645 non-null    str
dtypes: int64(2), str(2)
memory usage: 20.3 KB

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido
0,3500105,6504,Adamantina,Adamantina
1,3500204,6505,Adolfo,Adolfo
2,3500303,6506,Aguaí,Aguaí
3,3500402,6507,Águas da Prata,Águas da Prata
4,3500501,6508,Águas de Lindóia,Águas de Lindóia

In [5]:
# Lista Municípios
list_id_tjsp = list(df_municipios["id_municipio_tjsp"])
print(len(list_id_tjsp))

645

Obtemos todas as unidades de todos os municípios do TJSP.

In [6]:
df_unidades = listar_unidades.get_unidades_batch(
    list_id_tjsp=list(df_municipios["id_municipio_tjsp"])
)

# Results
df_unidades.info()
df_unidades.head()

<class 'pandas.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_municipio_tjsp  1310 non-null   int64
 1   raj                1310 non-null   str
 2   municipio_tjsp     1310 non-null   str
 3   comarca_tjsp       1310 non-null   str
 4   comarca_sede       1310 non-null   int64
 5   unidades           1310 non-null   str
dtypes: int64(2), str(4)
memory usage: 61.5 KB

,id_municipio_tjsp,raj,municipio_tjsp,comarca_tjsp,comarca_sede,unidades
0,6507,4ª RAJ Campinas,Águas da Prata,São João da Boa Vista,0,Cartório Anexo do Juizado Especial Cível - UNI...
1,6507,4ª RAJ Campinas,Águas da Prata,São João da Boa Vista,0,Fórum I Dr. Plínio Barreto
2,6508,4ª RAJ Campinas,Águas de Lindóia,Águas de Lindóia,1,Fórum Águas de Lindóia
3,6508,4ª RAJ Campinas,Águas de Lindóia,Águas de Lindóia,1,Fórum Águas de Lindóia (J.E.CÍVEL e Criminal)
4,6522,4ª RAJ Campinas,Americana,Americana,1,Fórum Americana

In [ ]:
filename = "Unidades, Municípios e Comarcas"

# Salva
df_unidades.to_csv(
    path_or_buf=output_path_tab / f"{filename}.csv",
    index=False,
)

Uma vez que temos a tabela de municípios e a tabela de comarcas/unidades, tratamos e juntamos

In [ ]:
display(listar_unidades.comarcas.info())
display(listar_unidades.comarcas.head(2))

In [ ]:

# lu.comarcas.to_excel(
#     excel_writer=output_path_tab / f"{filename}.xlsx",
#     sheet_name=f"{filename}",
#     index=False,
# )

In [ ]:
#passe df_tjsp_mun para df_tjsp

<br>

---

## Análises das Comarcas

Inicialmente conferi se o nome dos Municípios definido pelo TJSP correspondem ao nome das Comarcas que levantei!

Felizmente, pelo que analisei, a resposta é sim!

In [ ]:
# Read Data
df_tjsp = pd.read_csv(
    filepath_or_buffer=output_path_tab / "Unidades, Municípios e Comarcas.csv",
)

# Aplica strip em todo o dataframe
#df_tjsp = df_tjsp.map(lambda x: x.strip() if isinstance(x, str) else x)
df_tjsp = lu.unidades

# Results
df_tjsp.info()
df_tjsp.head()

In [ ]:
# Filtra Colunas
df_tjsp = df_tjsp.drop(
    labels=[
        'unidades',
        'raj',
        #'id_municipio_tjsp'
    ],
    axis='columns',
    errors='ignore',
)

df_tjsp = df_tjsp.drop_duplicates()
df_tjsp_mun = df_tjsp.copy()

# Results
df_tjsp_mun.info()
df_tjsp_mun.head()

<br>

Crio uma tabela temporária, apenas para conseguir, posteriormente, trazer os códigos do IBGE para a tabela das comarcas

In [ ]:
# Comarca
df_tjsp_com = df_tjsp[df_tjsp['comarca_sede'] == 1]

# Filtra Colunas
# df_tjsp_com = df_tjsp_com.drop(
#     labels=[
#         #'municipio_corrigido',
#         #'comarca_sede',
#         #'municipio_tjsp'
#         'eee'
#     ],
#     axis='columns',
#     errors='ignore',
# )

# Results
df_tjsp_com.info()
df_tjsp_com.head()

In [ ]:
# Filtra Colunas
df_tjsp_com = df_tjsp_com.drop(
    labels=["comarca_sede"],
    axis="columns",
    errors="ignore",
)

# Deletar Duplicados
df_tjsp_com = df_tjsp_com.drop_duplicates()

# Renomeia
df_tjsp_com = df_tjsp_com.rename(
    mapper={
        "municipio_tjsp_corrigido": "comarca_tjsp_corrigido",
        "id_municipio": "id_comarca",
    },
    axis="columns",
)

# Deleta
df_tjsp_com = df_tjsp_com.drop(
    labels=["municipio_tjsp"],
    axis="columns",
    errors="ignore",
)

# Bata Bater
df_tjsp_com = adjust_columns(
    df=df_tjsp_com,
    column_ajust="comarca_tjsp",
)

In [ ]:
# Results
df_tjsp_com.info()
df_tjsp_com.head()

In [ ]:
df_script1 = pd.read_csv(
    filepath_or_buffer=output_path_tab / "Comarcas e CJs.csv",
)
display(df_script1.head())

# Aplica strip em todo o dataframe
# Já inclui
# df_script1 = df_script1.map(lambda x: x.strip() if isinstance(x, str) else x)

# Ajusta Coluna
df_script1 = adjust_columns(df=df_script1, column_ajust="comarca_tjsp")
display(df_script1.head())

In [ ]:
# df_comarca[df_comarca['id_comarca'].isna()]

In [ ]:
filename = "Comarcas"

# Salva
df_comarca.to_csv(
    path_or_buf=output_path_tab / f"{filename}.csv",
    index=False,
)
# df_comarca.to_excel(
#     excel_writer=output_path_tab / f"{filename}.xlsx",
#     sheet_name=f"{filename}",
#     index=False,
# )

In [ ]:
for file in list(output_path_tab.glob('Comarcas e CJs*')):
    print(file)
    file.unlink()

<br>

---

## Municípios

Adiciona à tabela dos municípios as comarcas

In [ ]:
# Read Data
df_tjsp = pd.read_csv(
    filepath_or_buffer=output_path_tab / "Unidades, Municípios e Comarcas.csv",
)

# Results
df_tjsp.info()
df_tjsp.head()

In [ ]:
# Filtra Colunas
df_tjsp = df_tjsp.drop(
    labels=[
        'unidades',
        'raj',
        'municipio_tjsp',
        'municipio_tjsp_corrigido',
        #'id_municipio_tjsp',
    ],
    axis='columns',
    errors='ignore',
)

df_tjsp = df_tjsp.drop_duplicates()
df_tjsp_mun = df_tjsp.copy()
# df_tjsp_mun[df_tjsp_mun['municipio_tjsp'] == 'Charqueada']
df_tjsp_mun

In [ ]:
# Ajusta Coluna
df_tjsp_mun = adjust_columns(
    df=df_tjsp_mun,
    # column_ajust="municipio_tjsp",
    column_ajust="municipio_tjsp_corrigido",
)

<br>

---

### Municípios

In [ ]:
df_script3 = pd.read_csv(filepath_or_buffer=output_path_tab / 'Municipios.csv')

# Results
df_script3.info()
df_script3.head()

In [ ]:
# Ajusta Coluna
df_script3 = adjust_columns(df=df_script3, column_ajust='municipio_tjsp')

In [ ]:
# Merge
df_tjsp_merged = pd.merge(
    left=df_script3,
    right=df_tjsp_mun,
    left_on='municipio_tjsp_temp',
    right_on='municipio_tjsp_temp',
    how='left',
    suffixes=['', '_copy'],
)

# Results
df_tjsp_merged.info()
df_tjsp_merged.head()

In [ ]:
# Filtra Colunas
df_tjsp_merged = df_tjsp_merged.drop(
    labels=[
        'municipio_tjsp_temp',
        'id_municipio_tjsp_copy',
        'municipio_tjsp_copy',
        'id_municipio_copy',
    ],
    axis='columns',
    errors='ignore',
)

# Results
df_tjsp_merged.info()
df_tjsp_merged.head()

Uma vez que adicionei o nome da Comarca...\
Desejo converter para número...

Para isso eu leio a tabela de comarcas.

<br>

---

### Comarcas

In [ ]:
# Read Data
df_tjsp_com = pd.read_csv(filepath_or_buffer=output_path_tab / 'Comarcas.csv')

# Results
df_tjsp_com.info()
df_tjsp_com.head()

In [ ]:
df_tjsp_com = adjust_columns(df=df_tjsp_com, column_ajust='comarca_tjsp')
df_tjsp_com

In [ ]:
df_tjsp_merged = adjust_columns(df=df_tjsp_merged, column_ajust='comarca_tjsp')
df_tjsp_merged

In [ ]:
df_municipio = pd.merge(
    left=df_tjsp_merged,
    right=df_tjsp_com,
    left_on='comarca_tjsp_temp',
    right_on='comarca_tjsp_temp',
    how='left',
    suffixes=['', '_copy'],
)

# 
df_municipio = df_municipio.drop(
    labels=[
        'comarca_tjsp_temp',
        'comarca_tjsp_corrigido',
        'comarca_tjsp_copy',
        'comarca_tjsp',
    ],
    axis='columns',
)

# Results
df_municipio.info()
df_municipio.head()

In [ ]:
filename = "Municipios"

# Salva
df_municipio.to_csv(
    path_or_buf=output_path_tab / f"{filename}.csv",
    index=False,
)
df_municipio.to_excel(
    excel_writer=output_path_tab / f"{filename}.xlsx",
    sheet_name=f"{filename}",
    index=False,
)