<br>

# Municípios

Explorando o _site_ [ListaTelefonica](https://www.tjsp.jus.br/ListaTelefonica) foi possível encontrar APIs que operam e fazer diversas pesquisas.

In [16]:
from tjsp_unidades import extract
from tjsp_unidades.paths import output_path_tab

<br>

---

## Lista de Municípios

Criamos função que pega o Nome e Código do município, de acordo com o TJSP.

In [17]:
municipio = extract.Municipio()

In [18]:
# Apenas Exemplo da Função!
municipio.search(termo='San')

   id_municipio_tjsp            municipio_tjsp
0               6509    Águas de Santa Bárbara
1               6675  Espírito Santo do Pinhal
2               6676   Espírito Santo do Turvo
3               6892            Oscar Bressane
4               7000                    Rosana
5               7014               Sandovalina
6               7015              Santa Adélia
7               7016           Santa Albertina
8               7017     Santa Bárbara d'Oeste
9               7018              Santa Branca

Para termos um _input_ para a função, que é necessário inserir um termo para pesquisa.

Para obter diveresos termos, usei o nomes dos municípios que constam no projeto [open_geodata]().

In [19]:
municipio._lista_municipios[0:5]

['Adamantina', 'Adolfo', 'Aguaí', 'Águas da Prata', 'Águas de Lindóia']

<br>

Obtive o município com maior número de caracteres, visto que a função do método `POST` sempre lista apenas 10 municípios...

In [20]:
municipio._n_caracteres_mun_max

26

<br>

Uma vez com a função que retorna os municípios escrita, fiz uma iteração por todos os trechos de nomes de municípios. Para cada municípios foi pesquisado diversas vezes, incrementando o número de caracteres. Por exemplos, o município de Santos foi pesquisado:

- San
- Sant
- Santo
- Santos

<br>

Isso garantiu que todos os municípios foram "raspados".

In [21]:
municipio._list_termos[0:5]

São 4267 termos para pesquisa

['Adolf', 'Campo', 'Drac', 'Poti', 'São Vicen']

<br>

Antes eu levava cerca de 40 minutos para rodar. Ajustando o código, passei a levar 40 segundos.

In [22]:
# Obtem todos os IDs dos Municípios do TJSP
municipio.search_batch()

# Results
municipio.df_search.info()
municipio.df_search.head()

São 4267 termos para pesquisa
<class 'pandas.DataFrame'>
RangeIndex: 645 entries, 0 to 644
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_municipio_ibge         645 non-null    int64
 1   id_municipio_tjsp         645 non-null    int64
 2   municipio_tjsp            645 non-null    str
 3   municipio_tjsp_corrigido  645 non-null    str
dtypes: int64(2), str(2)
memory usage: 20.3 KB

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido
0,3500105,6504,Adamantina,Adamantina
1,3500204,6505,Adolfo,Adolfo
2,3500303,6506,Aguaí,Aguaí
3,3500402,6507,Águas da Prata,Águas da Prata
4,3500501,6508,Águas de Lindóia,Águas de Lindóia

<br>

Uma vez que sei os erros dos nomes e são apenas 3 registros...
Criei uma coluna duplicada para corrigir!

In [23]:
# Checa se foi substituido na coluna "Nome Corrigido"
mask = municipio.df_search["municipio_tjsp_corrigido"].str.startswith("Florí")
municipio.df_search[mask]

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido
186,3516101,6688,Florínia,Florínea

Ajusto a tabela criada

In [24]:
filename = "municipios"

# Salva
municipio.df_search.to_csv(
    path_or_buf=output_path_tab / f"{filename}.csv",
    index=False,
)

<br>

---

## Detalhes

In [25]:
# Apenas Exemplo da Função!
municipio.detalhe(id_municipio_tjsp=6504)

,id_municipio_tjsp,raj,municipio_tjsp,comarca_tjsp,comarca_sede,imovel
0,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum I Adamantina
1,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum II Adamantina (Residência Oficial)
2,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum III Adamantina - UAAJ - FAC. ADAM. INTEG...

In [26]:
municipio.detalhe_batch()

# Results
municipio.df_detalhes.info()
municipio.df_detalhes.head()

<class 'pandas.DataFrame'>
Index: 1306 entries, 0 to 1309
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_municipio_tjsp  1306 non-null   int64
 1   raj                1306 non-null   str
 2   municipio_tjsp     1306 non-null   str
 3   comarca_tjsp       1306 non-null   str
 4   comarca_sede       1306 non-null   int64
 5   imovel             1306 non-null   str
dtypes: int64(2), str(4)
memory usage: 71.4 KB

,id_municipio_tjsp,raj,municipio_tjsp,comarca_tjsp,comarca_sede,imovel
0,6512,10ª RAJ Sorocaba,Alambari,Itapetininga,0,Fórum Itapetininga I - (Desembargador Bernarde...
1,6512,10ª RAJ Sorocaba,Alambari,Itapetininga,0,Fórum Itapetininga II (Criminal) Juiz Paulo Ru...
2,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum I Adamantina
3,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum II Adamantina (Residência Oficial)
4,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum III Adamantina - UAAJ - FAC. ADAM. INTEG...

In [27]:
filename = "municipios_imovel"

# Salva
municipio.df_detalhes.to_csv(
    path_or_buf=output_path_tab / f"{filename}.csv",
    index=False,
)