<br>

# Imóveis


Por meio do _site_ [ListaTelefonica](https://www.tjsp.jus.br/ListaTelefonica) foi possível relevar as APIs que operam e fazer diversas pesquisas.

<br>

Michel Metran\
Data: 18.06.2024\
Atualizado em: 12.08.2026

In [1]:
from tjsp_unidades import extract
from tjsp_unidades.paths import output_path_tab

<br>

---

## Lista de Imóveis

<br>

---

### Municípios

Inicialmente se faz necessário listar de imóveis, que está na tabela de detalhes dos municípios.

In [2]:
# Listar Unidades
municipio = extract.Municipio()
municipio.search_batch()
municipio.detalhe_batch()

São 4267 termos para pesquisa

,id_municipio_tjsp,raj,municipio_tjsp,comarca_tjsp,comarca_sede,imovel
0,6507,4ª RAJ Campinas,Águas da Prata,São João da Boa Vista,0,Cartório Anexo do Juizado Especial Cível - UNI...
1,6507,4ª RAJ Campinas,Águas da Prata,São João da Boa Vista,0,Fórum I Dr. Plínio Barreto
2,6533,10ª RAJ Sorocaba,Apiaí,Apiaí,1,Fórum Apiaí - Des. Déscio Mendes Pereira
3,6530,5ª RAJ Presidente Prudente,Anhumas,Presidente Prudente,0,Fórum Presidente Prudente - Francisco de Souza...
4,6530,5ª RAJ Presidente Prudente,Anhumas,Presidente Prudente,0,Fórum Presidente Prudente II (CEJUSC)
...,...,...,...,...,...,...
1305,6513,5ª RAJ Presidente Prudente,Alfredo Marcondes,Presidente Prudente,0,Fórum Presidente Prudente - Francisco de Souza...
1306,6513,5ª RAJ Presidente Prudente,Alfredo Marcondes,Presidente Prudente,0,Fórum Presidente Prudente II (CEJUSC)
1307,6526,4ª RAJ Campinas,Analândia,Itirapina,0,Desembargador Lafayette Salles Júnior
1308,6509,3ª RAJ Bauru,Águas de Santa Bárbara,Cerqueira César,0,Fórum Cerqueira César
1309,6517,10ª RAJ Sorocaba,Alumínio,Mairinque,0,Fórum Mairinque

<br>

Uma vez com a função que obter os dados das Unidades e, PRINCIPALMENTE, obter as comarcas!
Foi possível iterar pelos 645 municípios para pegar as informações dos imóveis.

<br>

---

### Imóveis

In [3]:
imovel = extract.Imovel(municipio=municipio)

<br>

Uma vez com a lista de todos os municípios e seus respectivos códigos, foi possível obter as informações dos fóruns por meio de outro método `POST`.

In [4]:
imovel.search(termo='forum')

   id_imovel                                        imovel_tjsp
3          3                             Fórum Águas de Lindóia
5          4                                       Fórum Agudos
6          5                                  Fórum Altinópolis
7          6                                    Fórum Americana
9          7                          Fórum Américo Brasiliense
1        172      Fórum "Juiz Eleutério Dutra Filho" - Mongaguá
2        245  Fórum "Juiz Messias José de Melo Souza" (Sales...
4        415      Fórum Águas de Lindóia (J.E.CÍVEL e Criminal)
0        435         ANEXO FISCAL - Fórum Santa Bárbara d´Oeste
8        631                  Fórum Americana (CEJUSC) - UNISAL

<br>

Há também alguns métodos privados

```python
imovel._n_caracteres_mun_max
imovel._list_termos
```

In [5]:
imovel.search_batch()

# Results
imovel.df_search.info()
imovel.df_search.head()

São 3192 termos para pesquisa
<class 'pandas.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_imovel    640 non-null    int64
 1   imovel_tjsp  640 non-null    str
dtypes: int64(1), str(1)
memory usage: 10.1 KB

   id_imovel             imovel_tjsp
0          1      Fórum I Adamantina
1          2          Fórum de Aguaí
2          3  Fórum Águas de Lindóia
3          4            Fórum Agudos
4          5       Fórum Altinópolis

<br>

Pesquisa de um imóvel qualquer

In [6]:
mask = imovel.df_search["id_imovel"] == 240
imovel.df_search[mask]["imovel_tjsp"].values

<StringArray>
['Tribunal de Justiça da Comarca de Ribeirão Preto - Prédio I']
Length: 1, dtype: str

<br>

---

## Detalhes

É possível consultar detalhes de um imóvel

In [7]:
id_imovel = 291

In [8]:
imovel.detalhe(id_imovel=id_imovel)

,id_imovel,imovel,endereco,telefone,fax,email,cj,num_varas_instaladas,entrancia,comarca_tjsp,dist_capital,tensao_eletrica
0,291,Fórum Taquaritinga I,"Rua Duque de Caxias , 267 - Centro - CEP 15900...",(16) 3253-9840;,Não Informado,taquaritingaadm@tjsp.jus.br,Jaboticabal,4,Entrância Inicial,Taquaritinga,305.93 Km,110V

<br>

O método `obter_imovel` reflete um _endpoint_ do TJSP que é público. Contudo, ao que tudo indicada, ele retorna o mesmo que o método `detalhe`.

In [9]:
imovel.obter_imovel(id_imovel=id_imovel)

,id_imovel,imovel,endereco,telefone,fax,email,cj,num_varas_instaladas,entrancia,comarca_tjsp,dist_capital,tensao_eletrica
0,291,Fórum Taquaritinga I,"Rua Duque de Caxias , 267 - Centro - CEP 15900...",(16) 3253-9840;,Não Informado,taquaritingaadm@tjsp.jus.br,Jaboticabal,4,Entrância Inicial,Taquaritinga,305.93 Km,110V

<br>

E é possível fazer isso em modo _batch_, ou seja, pesquisando **em lote**. Para esse método eu, inicialmente, usava parte do nome das unidades (que obtive juntamente com os municípios), para pesquisar. Observei que nem todos os imóveis eram mapeados com esse método, dai "chumbei" no código a iteração entre 0 e 1200.

In [10]:
# Detalhes dos Imóveis
imovel.detalhe_batch()

# Results
imovel.df_detalhes.info()
imovel.df_detalhes.head()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_imovel             918 non-null    int64
 1   imovel                918 non-null    str
 2   telefone              918 non-null    str
 3   fax                   918 non-null    str
 4   email                 918 non-null    str
 5   cj                    918 non-null    str
 6   num_varas_instaladas  918 non-null    int64
 7   entrancia             918 non-null    str
 8   comarca_tjsp          918 non-null    str
 9   dist_capital          675 non-null    float64
 10  tensao_eletrica       918 non-null    str
 11  endereco_lougradouro  918 non-null    str
 12  endereco_cep          918 non-null    str
 13  endereco_municipio    918 non-null    str
 14  endereco_uf           918 non-null    str
dtypes: float64(1), int64(2), str(12)
memory usage: 107.7 KB

,id_imovel,imovel,telefone,fax,email,cj,num_varas_instaladas,entrancia,comarca_tjsp,dist_capital,tensao_eletrica,endereco_lougradouro,endereco_cep,endereco_municipio,endereco_uf
0,1,Fórum I Adamantina,(18) 2106-1718,Não Informado,adamantinaadm@tjsp.jus.br,Tupã,3,Entrância Inicial,Adamantina,500.26,110V,"Avenida Ademar de Barros , 133 - Centro",17800-000,Adamantina,SP
1,2,Comarca de Aguaí,Não Informado,Não Informado,aguaiadm@tjsp.jus.br,São João da Boa Vista,1,Entrância Inicial,Aguaí,169.25,110V,"Rua Joaquim Paula Cruz , 900 - Jd. Sta. Úrsula",13863-044,Aguaí,SP
2,3,Fórum Águas de Lindóia,(19) 2154-5204,Não Informado,aguaslindoiaadm@tjsp.jus.br,Amparo,1,Entrância Inicial,Águas de Lindóia,119.20,110V,"Rua Francisco Spartani , 66 - Jd. Le Villete",13940-000,Águas de Lindóia,SP
3,4,"FÓRUM DESEMBARGADOR ""FRANCISCO MEIRELLES DOS S...",(14) 2151-5455,Não Informado,agudosadm@tjsp.jus.br,Bauru,2,Entrância Inicial,Agudos,268.95,110V,"Rua Paulo Nelli , 276 - Vila Andreotti",17120-370,Agudos,SP
4,5,"Fórum ""Desembargador ALFREDO FANUCCHI NETO""",(16) 3665-2211,Não Informado,altinopadm@tjsp.jus.br,Batatais,1,Entrância Inicial,Altinópolis,290.52,110V,"Avenida Doutor Alberto Crivelenti , 555 - Centro",14350-005,Altinópolis,SP

<br>

Com isso chegamos à 321 comarcas. Acredito que o erro da Vila Mimosa esteja também aqui.

In [11]:
len(set(imovel.df_detalhes['comarca_tjsp']))

321

<br>

Não está!

In [12]:
mask = imovel.df_detalhes['comarca_tjsp'].str.contains('Vila')
imovel.df_detalhes[mask]

Empty DataFrame
Columns: [id_imovel, imovel, telefone, fax, email, cj, num_varas_instaladas, entrancia, comarca_tjsp, dist_capital, tensao_eletrica, endereco_lougradouro, endereco_cep, endereco_municipio, endereco_uf]
Index: []

<br>

Salvamos o resultado.

In [13]:
imovel.df_detalhes.to_csv(
    path_or_buf=output_path_tab / "imovel.csv",
    index=False,
)