<br>

# Imóveis


Por meio do _site_ [ListaTelefonica](https://www.tjsp.jus.br/ListaTelefonica) foi possível relevar as APIs que operam e fazer diversas pesquisas.

<br>

Michel Metran\
Data: 18.06.2024\
Atualizado em: 12.08.2026

In [ ]:
from tjsp_unidades import extract
from tjsp_unidades.paths import output_path_tab

In [ ]:
import pprint
import re

import pandas as pd
from bs4 import BeautifulSoup

<br>

---

## Lista de Imóveis

<br>

---

### Municípios

Inicialmente se faz necessário listar de imóveis, que está na tabela de detalhes dos municípios.

In [ ]:
# Listar Unidades
municipio = extract.Municipio()
municipio.search_batch()
municipio.detalhe_batch()

<br>

Uma vez com a função que obter os dados das Unidades e, PRINCIPALMENTE, obter as comarcas!
Foi possível iterar pelos 645 municípios para pegar as informações dos imóveis.

<br>

---

### Imóveis

In [ ]:
imovel = extract.Imovel(municipio=municipio)

<br>

Uma vez com a lista de todos os municípios e seus respectivos códigos, foi possível obter as informações dos fóruns por meio de outro método `POST`.

In [ ]:
imovel.search(termo='forum')

<br>

Há também alguns métodos privados

```python
imovel._n_caracteres_mun_max
imovel._list_termos
```

In [12]:
imovel.search_batch()

# Results
imovel.df_search.info()
imovel.df_search.head()

São 3192 termos para pesquisa
<class 'pandas.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_imovel    640 non-null    int64
 1   imovel_tjsp  640 non-null    str
dtypes: int64(1), str(1)
memory usage: 10.1 KB

   id_imovel             imovel_tjsp
0          1      Fórum I Adamantina
1          2          Fórum de Aguaí
2          3  Fórum Águas de Lindóia
3          4            Fórum Agudos
4          5       Fórum Altinópolis

<br>

Pesquisa de um imóvel qualquer

In [13]:
mask = imovel.df_search["id_imovel"] == 240
imovel.df_search[mask]["imovel_tjsp"].values

<StringArray>
['Tribunal de Justiça da Comarca de Ribeirão Preto - Prédio I']
Length: 1, dtype: str

<br>

---

## Detalhes

É possível consultar detalhes de um imóvel

In [ ]:
id_imovel = 291

In [15]:
imovel.detalhe(id_imovel=id_imovel)

,id_imovel,imovel,endereco,telefone,fax,email,cj,num_varas_instaladas,entrancia,comarca_tjsp,dist_capital,tensao_eletrica
0,291,Fórum Taquaritinga I,"Rua Duque de Caxias , 267 - Centro - CEP 15900...",(16) 3253-9840;,Não Informado,taquaritingaadm@tjsp.jus.br,Jaboticabal,4,Entrância Inicial,Taquaritinga,305.93 Km,110V

<br>

O método `obter_imovel` reflete um _endpoint_ do TJSP que é público. Contudo, ao que tudo indicada, ele retorna o mesmo que o método `detalhe`.

In [ ]:
imovel.obter_imovel(id_imovel=id_imovel)

<br>

E é possível fazer isso em modo _batch_, ou seja, pesquisando **em lote**. Para esse método eu, inicialmente, usava parte do nome das unidades (que obtive juntamente com os municípios), para pesquisar. Observei que nem todos os imóveis eram mapeados com esse método, dai "chumbei" no código a iteração entre 0 e 1200.

In [ ]:
imovel.detalhe_batch()

In [ ]:
1+a

<br>

Com isso chegamos à 321 comarcas. Acredito que o erro da Vila Mimosa esteja também aqui.

In [ ]:
len(set(imovel.df_detalhes['comarca_tjsp']))

<br>

Não está!

In [ ]:
mask = imovel.df_detalhes['comarca_tjsp'].str.contains('Vila')
imovel.df_detalhes[mask]

<br>

Salvamos o resultado.

In [ ]:
imovel.df_detalhes.to_csv(
    path_or_buf=output_path_tab / "imovel.csv",
    index=False,
)

In [ ]:
df_detalhes = imovel.df_detalhes.copy()
df_detalhes.info()
df_detalhes.head()