In [1]:
import concurrent.futures
import logging
import pprint

import pandas as pd
from bs4 import BeautifulSoup
from more_itertools import one

from tjsp_unidades import extract
from tjsp_unidades.paths import output_path_tab

<br>

---

## Lista de Imóveis

<br>

---

### Listar Unidades

Inicialmente se faz necessário listar unidades

In [2]:
# Listar Unidades
listar_unidades = extract.ListarUnidades()

# Read Data
df_municipios = pd.read_csv(
    filepath_or_buffer=output_path_tab / "Municipios.csv",
)
display(df_municipios.head())

# Lista Municípios
list_id_tjsp = list(df_municipios["id_municipio_tjsp"])
print(len(list_id_tjsp))

df_unidades = listar_unidades.get_unidades_batch(
    list_id_tjsp=list(df_municipios["id_municipio_tjsp"])
)

# Results
df_unidades.info()
df_unidades.head()

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido
0,3500105,6504,Adamantina,Adamantina
1,3500204,6505,Adolfo,Adolfo
2,3500303,6506,Aguaí,Aguaí
3,3500402,6507,Águas da Prata,Águas da Prata
4,3500501,6508,Águas de Lindóia,Águas de Lindóia

645
<class 'pandas.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_municipio_tjsp  1310 non-null   int64
 1   raj                1310 non-null   str
 2   municipio_tjsp     1310 non-null   str
 3   comarca_tjsp       1310 non-null   str
 4   comarca_sede       1310 non-null   int64
 5   imoveis            1310 non-null   str
dtypes: int64(2), str(4)
memory usage: 61.5 KB

,id_municipio_tjsp,raj,municipio_tjsp,comarca_tjsp,comarca_sede,imoveis
0,6514,8ª RAJ São José do Rio Preto,Altair,Olímpia,0,Fórum Olímpia I - (Principal)
1,6514,8ª RAJ São José do Rio Preto,Altair,Olímpia,0,Fórum Olímpia II (3ª Vara Cível)
2,6514,8ª RAJ São José do Rio Preto,Altair,Olímpia,0,Fórum Olímpia III - (Vara do Juizado Especial ...
3,6514,8ª RAJ São José do Rio Preto,Altair,Olímpia,0,Fórum Olímpia IV - (Setor das Execuções Fiscais)
4,6514,8ª RAJ São José do Rio Preto,Altair,Olímpia,0,Fórum Olímpia V - (CEJUSC)

<br>

---

### Imóveis

In [3]:
listar_imovel = extract.ListarImoveis(listar_unidades=listar_unidades)
listar_imovel

In [4]:
listar_imovel.get_imovel(termo='Forum')

   id_imovel                                        imovel_tjsp
0        435         ANEXO FISCAL - Fórum Santa Bárbara d´Oeste
1        172      Fórum "Juiz Eleutério Dutra Filho" - Mongaguá
2        245  Fórum "Juiz Messias José de Melo Souza" (Sales...
3          3                             Fórum Águas de Lindóia
4        415      Fórum Águas de Lindóia (J.E.CÍVEL e Criminal)
5          4                                       Fórum Agudos
6          5                                  Fórum Altinópolis
7          6                                    Fórum Americana
8        631                  Fórum Americana (CEJUSC) - UNISAL
9          7                          Fórum Américo Brasiliense

In [ ]:
listar_imovel.n_caracteres_mun_max

In [ ]:
listar_imovel.list_termos

In [ ]:
listar_imovel.request()

In [ ]:
listar_imovel.df_imovel

In [ ]:
listar_imovel.df_imovel[listar_imovel.df_imovel["id_imovel"] == 240]['imovel_tjsp'].values

<br>

------

## Obter Imovel

In [ ]:
imovel_busca = extract.ObterImovel()
r = imovel_busca.get(id_imovel=59)
# BS4
soup = BeautifulSoup(r.text, "html.parser")
pprint.pprint(soup.prettify())

<br>

---

## Imóvel Busca

In [ ]:
imovel_busca = extract.ImovelBusca()
r = imovel_busca.get(id_imovel=59)
r

In [ ]:
# BS4
soup = BeautifulSoup(r.text, "html.parser")
pprint.pprint(soup.prettify())