<br>

# Setores

In [ ]:
import pprint

from bs4 import BeautifulSoup

from tjsp_unidades import extract
from tjsp_unidades.paths import output_path_tab

In [ ]:
import concurrent.futures
import logging

import pandas as pd
from more_itertools import one

<br>

---

## Lista de Setores

<br>

---

### Municípios

Inicialmente se faz necessário listar de imóveis, que está na tabela de detalhes dos municípios.

In [3]:
# Listar Unidades
municipio = extract.Municipio()
municipio.search_batch()
municipio.detalhe_batch()

São 4267 termos para pesquisa

,id_municipio_tjsp,raj,municipio_tjsp,comarca_tjsp,comarca_sede,imovel
0,6510,4ª RAJ Campinas,Águas de São Pedro,São Pedro,0,"Fórum ""Francisco Mendes de Aguiar"""
1,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum I Adamantina
2,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum II Adamantina (Residência Oficial)
3,6504,5ª RAJ Presidente Prudente,Adamantina,Adamantina,1,Fórum III Adamantina - UAAJ - FAC. ADAM. INTEG...
4,6513,5ª RAJ Presidente Prudente,Alfredo Marcondes,Presidente Prudente,0,Fórum Presidente Prudente - Francisco de Souza...
...,...,...,...,...,...,...
1305,7147,3ª RAJ Bauru,Chavantes,Chavantes,1,Fórum Chavantes
1306,7147,3ª RAJ Bauru,Chavantes,Chavantes,1,Fórum (Segundo Prédio)
1307,7133,4ª RAJ Campinas,Valinhos,Valinhos,1,Fórum Valinhos I - (Principal)
1308,7133,4ª RAJ Campinas,Valinhos,Valinhos,1,Fórum Valinhos II - (Vara do Juizado Especial ...
1309,7133,4ª RAJ Campinas,Valinhos,Valinhos,1,Fórum Valinhos III - (Setor das Execuções Fisc...

<br>

---

### Imóveis

In [6]:
imovel = extract.Imovel(municipio=municipio)
imovel.search_batch()

São 3192 termos para pesquisa

     id_imovel                                        imovel_tjsp
0            1                                 Fórum I Adamantina
1            2                                     Fórum de Aguaí
2            3                             Fórum Águas de Lindóia
3            4                                       Fórum Agudos
4            5                                  Fórum Altinópolis
..         ...                                                ...
635        968  Fórum Francisco Morato V - CEJUSC (Defensoria ...
636        969  Fórum da Barra Funda - Anexo da Infância e da ...
637        970                             Mairiporâ III - CEJUSC
638        971                      CEJUSC II – UAAJ UNIGUARULHOS
639        972  Fórum Bauru - UPJ 1ª E 2ª VARAS DE VIOLÊNCIA D...

[640 rows x 2 columns]

In [7]:
# Desenvolver
imovel.detalhe_batch()

,id_imovel,imovel,telefone,fax,email,cj,num_varas_instaladas,entrancia,comarca_tjsp,dist_capital,tensao_eletrica,endereco_lougradouro,endereco_cep,endereco_municipio,endereco_uf
0,1,Fórum I Adamantina,(18) 2106-1718,Não Informado,adamantinaadm@tjsp.jus.br,Tupã,3,Entrância Inicial,Adamantina,500.26,110V,"Avenida Ademar de Barros , 133 - Centro",17800-000,Adamantina,SP
1,2,Comarca de Aguaí,Não Informado,Não Informado,aguaiadm@tjsp.jus.br,São João da Boa Vista,1,Entrância Inicial,Aguaí,169.25,110V,"Rua Joaquim Paula Cruz , 900 - Jd. Sta. Úrsula",13863-044,Aguaí,SP
2,3,Fórum Águas de Lindóia,(19) 2154-5204,Não Informado,aguaslindoiaadm@tjsp.jus.br,Amparo,1,Entrância Inicial,Águas de Lindóia,119.20,110V,"Rua Francisco Spartani , 66 - Jd. Le Villete",13940-000,Águas de Lindóia,SP
3,4,"FÓRUM DESEMBARGADOR ""FRANCISCO MEIRELLES DOS S...",(14) 2151-5455,Não Informado,agudosadm@tjsp.jus.br,Bauru,2,Entrância Inicial,Agudos,268.95,110V,"Rua Paulo Nelli , 276 - Vila Andreotti",17120-370,Agudos,SP
4,5,"Fórum ""Desembargador ALFREDO FANUCCHI NETO""",(16) 3665-2211,Não Informado,altinopadm@tjsp.jus.br,Batatais,1,Entrância Inicial,Altinópolis,290.52,110V,"Avenida Doutor Alberto Crivelenti , 555 - Centro",14350-005,Altinópolis,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,968,Fórum Francisco Morato V - CEJUSC (Defensoria ...,(11) 4489-8701,Não Informado,Não Informado,Jundiaí,0,Entrância Final,Francisco Morato,31.60,110V,"Rua Progresso , 110 - Centro",07910-170,Francisco Morato,SP
914,969,Fórum da Barra Funda - Anexo da Infância e da ...,Não Informado,Não Informado,Não Informado,São Paulo,5,Não Informado,São Paulo,0.00,110V,"Rua José Gomes Falcão , 156 - Portão F - Barra...",01139-010,São Paulo,SP
915,970,Mairiporâ III - CEJUSC,(11) 4419-1820,Não Informado,Não Informado,Guarulhos,0,Entrância Inicial,Mairiporã,25.95,110V,"Alameda Tibiriçá , 1103 - Vila Ipanema",07600-084,Mairiporã,SP
916,971,CEJUSC II – UAAJ UNIGUARULHOS,Não Informado,Não Informado,Não Informado,Guarulhos,0,Entrância Final,Guarulhos,14.13,110V,"Praça Tereza Cristina , 88 - Centro",07023-070,Guarulhos,SP
917,972,Fórum Bauru - UPJ 1ª E 2ª VARAS DE VIOLÊNCIA D...,Não Informado,Não Informado,Não Informado,Bauru,2,Entrância Final,Bauru,283.65,110V,"Rua Silva Jardim , 2-77 - Bela Vista",17060-240,Bauru,SP

<br>

---

### Listar Unidades

Inicialmente se faz necessário listar unidades

<br>

---

### Setores

In [8]:
setores = extract.Setores(municipio=municipio)
setores

In [9]:
setores.search(termo='Forum')

   id_setor                                         setor_tjsp
7      4699  21º ao 25º Ofício Cível (UPJ III – Unidade de ...
8      4715  26º ao 30º Ofício Cível (UPJ II – Unidade de P...
2      4762  Seção Administrativa – Turno da Manhã | Fórum ...
9      4764  31º ao 35º Ofício Cível (UPJ IV – Unidade de P...
6     15453  16º ao 20º Ofício Cível (UPJ V – Unidade de Pr...
3     15815  01º ao 5º Ofício Cível (UPJ VI – Unidade de Pr...
4     15817  06º ao 10º Ofício Cível (UPJ VIII – Unidade de...
5     15818  11º ao 15º Ofício Cível (UPJ IX – Unidade de P...
0     16424  Seção Administrativa – Turno da Manhã | Fórum ...
1     16884  Seção Administrativa – Turno da Manhã | Fórum ...

<br>

Métodos privados

```python
setores._n_caracteres_mun_max
setores._list_termos
```

In [10]:
setores.search_batch()

setores.df_search.info()
setores.df_search.head()

São 13176 termos para pesquisa

Erro ao processar o termo '1ª': DataFrame constructor not properly called!
Erro ao processar o termo 'Fórum Bauru II - Fazenda Púb': HTTPSConnectionPool(host='www.tjsp.jus.br', port=443): Max retries exceeded with url: /AutoComplete/ListarSetores (Caused by ConnectTimeoutError(<HTTPSConnection(host='www.tjsp.jus.br', port=443) at 0x1fc55f85ee0>, 'Connection to www.tjsp.jus.br timed out. (connect timeout=60)'))
Erro ao processar o termo 'DR': DataFrame constructor not properly called!

<class 'pandas.DataFrame'>
RangeIndex: 3178 entries, 0 to 3177
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_setor    3178 non-null   int64
 1   setor_tjsp  3178 non-null   str
dtypes: int64(1), str(1)
memory usage: 49.8 KB

   id_setor                                         setor_tjsp
0         1  Juizado Especial Cível, Criminal e da Fazenda ...
1         2              3ª Vara Judicial | Fórum I Adamantina
2         3            3º Ofício Judicial | Fórum I Adamantina
3         4              2ª Vara Judicial | Fórum I Adamantina
4         5            1º Ofício Judicial | Fórum I Adamantina

In [11]:
setores.df_search.tail()

      id_setor                                         setor_tjsp
3173     17228   Distribuidor | Fórum Guaratinguetá I (Principal)
3174     17229  Juizado Cível | Fórum Guaratinguetá I (Principal)
3175     17230  Juizado Criminal | Fórum Guaratinguetá I (Prin...
3176     17235                   Administração | Fórum I Barretos
3177     17248  Anexo de Violência Doméstica e Familiar contra...

<br>

---

## Detalhe

Fazer o modo _batch_

In [12]:
r, dd = setores.detalhe(id_setor=4146)

dd

{'setor': '1ª Vara Judicial',
 'codigo_imovel': '291',
 'detalhes': {'Dados Gerais': 'GABINETE DO JUIZ',
  'Telefone Principal': '(16) Não Informado',
  'Fax': '(16) Não Informado',
  'Telefone': '(16) 3253-9833',
  'Email Setor': 'Não Informado'}}

Explorar

In [13]:
# BS4
soup = BeautifulSoup(r.text, "html.parser")
pprint.pprint(soup.prettify())

('<div class="col-md-9">\n'
 ' <h2 class="setortitle">\n'
 '  1ª Vara Judicial\n'
 ' </h2>\n'
 ' <div class="lista-dados">\n'
 '  <h2>\n'
 '   DETALHES DO SETOR\n'
 '  </h2>\n'
 '  <div>\n'
 '   <dl class="dl-horizontal dl-lista-telefonica">\n'
 '    <dt>\n'
 '     Dados Gerais\n'
 '    </dt>\n'
 '    <dd>\n'
 '     GABINETE DO JUIZ\n'
 '    </dd>\n'
 '   </dl>\n'
 '   <dl class="dl-horizontal dl-lista-telefonica">\n'
 '    <dt>\n'
 '     Telefone Principal\n'
 '    </dt>\n'
 '    <dd>\n'
 '     <span>\n'
 '      (16) Não Informado;\n'
 '     </span>\n'
 '    </dd>\n'
 '   </dl>\n'
 '   <dl class="dl-horizontal dl-lista-telefonica">\n'
 '    <dt>\n'
 '     Fax\n'
 '    </dt>\n'
 '    <dd>\n'
 '     <span>\n'
 '      (16) Não Informado;\n'
 '     </span>\n'
 '    </dd>\n'
 '   </dl>\n'
 '   <dl class="dl-horizontal dl-lista-telefonica">\n'
 '    <dt>\n'
 '     Telefone\n'
 '    </dt>\n'
 '    <dd>\n'
 '     <span>\n'
 '      (16) 3253-9833;\n'
 '     </span>\n'
 '    </dd>\n'
 '   </dl>\n'
 '   <dl class="dl-horizontal dl-lista-telefonica">\n'
 '    <dt>\n'
 '     Email Setor\n'
 '    </dt>\n'
 '    <dd>\n'
 '     <span>\n'
 '      Não Informado;\n'
 '     </span>\n'
 '    </dd>\n'
 '   </dl>\n'
 '  </div>\n'
 '  <input id="hdCodigoImovel" type="hidden" value="291"/>\n'
 ' </div>\n'
 '</div>\n')

In [14]:
# 1. Extrair o Nome do Setor
nome_setor = soup.find("h2", class_="setortitle").get_text(strip=True)

# 2. Extrair os pares Chave/Valor da lista de dados
dados = {}
for dl in soup.find_all("dl", class_="dl-lista-telefonica"):
    chave = dl.find("dt").get_text(strip=True)
    # Rmove o ponto e vírgula e espaços em branco do final
    valor = dl.find("dd").get_text(strip=True).rstrip(";").strip()
    dados[chave] = valor

# 3. Extrair o Código do Imóvel (caso precise)
codigo_imovel = soup.find("input", id="hdCodigoImovel")["value"]

# Exibir os resultados
print(f"Setor: {nome_setor}")
print(f"Código Imóvel: {codigo_imovel}")
print("\nDetalhes:")
for chave, valor in dados.items():
    print(f"  {chave}: {valor}")

Setor: 1ª Vara Judicial
Código Imóvel: 291

Detalhes:
  Dados Gerais: GABINETE DO JUIZ
  Telefone Principal: (16) Não Informado
  Fax: (16) Não Informado
  Telefone: (16) 3253-9833
  Email Setor: Não Informado