<br>

# Setores

In [1]:
import pprint

import pandas as pd
from bs4 import BeautifulSoup

from tjsp_unidades import extract
from tjsp_unidades.paths import output_path_tab

In [2]:
import concurrent.futures
import logging

from more_itertools import one

<br>

---

## Lista de Setores

<br>

---

### Municípios

Inicialmente se faz necessário listar de imóveis, que está na tabela de detalhes dos municípios.

In [3]:
# Listar Unidades
municipio = extract.Municipio()
municipio.search_batch()
municipio.detalhe_batch()

São 4267 termos para pesquisa

,id_municipio_tjsp,raj,municipio_tjsp,comarca_tjsp,comarca_sede,imovel
0,6506,4ª RAJ Campinas,Aguaí,Aguaí,1,Comarca de Aguaí
1,6511,3ª RAJ Bauru,Agudos,Agudos,1,"FÓRUM DESEMBARGADOR ""FRANCISCO MEIRELLES DOS S..."
2,6505,8ª RAJ São José do Rio Preto,Adolfo,José Bonifácio,0,Fórum José Bonifácio - II (CEJUSC)
3,6505,8ª RAJ São José do Rio Preto,Adolfo,José Bonifácio,0,Fórum José Bonifácio I (Principal)
4,6508,4ª RAJ Campinas,Águas de Lindóia,Águas de Lindóia,1,Fórum Águas de Lindóia
...,...,...,...,...,...,...
1305,7145,8ª RAJ São José do Rio Preto,Votuporanga,Votuporanga,1,Fórum Votuporanga III - (CEJUSC)
1306,7147,3ª RAJ Bauru,Chavantes,Chavantes,1,Fórum Chavantes
1307,7147,3ª RAJ Bauru,Chavantes,Chavantes,1,Fórum (Segundo Prédio)
1308,7137,1ª RAJ Grande São Paulo,Vargem Grande Paulista,Vargem Grande Paulista,1,Desembargador HELIO DE QUADROS ARRUDA
1309,7141,8ª RAJ São José do Rio Preto,Viradouro,Viradouro,1,Gabriel Custódio da Silveira

<br>

---

### Imóveis

In [4]:
imovel = extract.Imovel(municipio=municipio)
imovel.search_batch()

São 3192 termos para pesquisa

     id_imovel                                        imovel_tjsp
0            1                                 Fórum I Adamantina
1            2                                     Fórum de Aguaí
2            3                             Fórum Águas de Lindóia
3            4                                       Fórum Agudos
4            5                                  Fórum Altinópolis
..         ...                                                ...
635        968  Fórum Francisco Morato V - CEJUSC (Defensoria ...
636        969  Fórum da Barra Funda - Anexo da Infância e da ...
637        970                             Mairiporâ III - CEJUSC
638        971                      CEJUSC II – UAAJ UNIGUARULHOS
639        972  Fórum Bauru - UPJ 1ª E 2ª VARAS DE VIOLÊNCIA D...

[640 rows x 2 columns]

In [ ]:
imovel.detalhe_batch()

<br>

---

### Listar Unidades

Inicialmente se faz necessário listar unidades

In [ ]:
# Listar Unidades
listar_unidades = extract.ListarUnidades()

# Read Data
df_municipios = pd.read_csv(
    filepath_or_buffer=output_path_tab / "Municipios.csv",
)
display(df_municipios.head())

# Lista Municípios
list_id_tjsp = list(df_municipios["id_municipio_tjsp"])
print(len(list_id_tjsp))

df_unidades = listar_unidades.get_unidades_batch(
    list_id_tjsp=list(df_municipios["id_municipio_tjsp"])
)

# Results
df_unidades.info()
df_unidades.head()

<br>

---

### Setores

In [ ]:
setores = extract.Setores(listar_unidades=listar_unidades)
setores

In [ ]:
setores.search(termo='Forum')

In [ ]:
setores._n_caracteres_mun_max

In [ ]:
setores._list_termos

In [ ]:
setores.search_batch()

In [ ]:
setores.df_search.head(50)

<br>

---

## Setor Busca

In [ ]:
r = setores.detalhe(id_setor=4146)
r

Explorar

In [ ]:
# BS4
soup = BeautifulSoup(r.text, "html.parser")
pprint.pprint(soup.prettify())

In [ ]:
text_comarca = soup.find_all("h4")
if text_comarca == []:
    raise RuntimeError("Erro")