<br>

# Transform

In [1]:
import pandas as pd

from tjsp_unidades import extract
from tjsp_unidades.transform.small_functions import adjust_columns

<br>

---

## Get Data

<br>

---

### Quem Somos

In [ ]:
quem_somos = extract.QuemSomos()

In [7]:
quem_somos.rajs.head(2)

,id_raj,raj_nome,raj_sigla,raj_regiao,juiz_diretor_nome,juiz_diretor_email
0,1,1ª RAJ - Grande São Paulo,1ª RAJ,Grande São Paulo,Fernando Antonio Tasso,daraj1@tjsp.jus.br
1,2,2ª RAJ - Araçatuba,2ª RAJ,Araçatuba,Antonio Fernando Sanches Batagelo,daraj2@tjsp.jus.br

In [8]:
quem_somos.cjs.head(2)

   id_cj cj_sigla                      cj_nome  id_raj
0      0  Capital                      Capital       1
1      1    1ª CJ  1ª Circunscrição Judiciária       7

In [9]:
quem_somos.comarcas.head(2)

São 321 comarcas

  comarca_tjsp  id_cj
0   Adamantina     30
1        Aguaí     50

<br>

---

### Municípios

In [12]:
municipio = extract.Municipio()

In [14]:
# Obtem todos os IDs dos Municípios do TJSP
municipio.search_batch()

# Results
municipio.df_search.info()
municipio.df_search.head()

São 4267 termos para pesquisa
<class 'pandas.DataFrame'>
RangeIndex: 645 entries, 0 to 644
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_municipio_ibge         645 non-null    int64
 1   id_municipio_tjsp         645 non-null    int64
 2   municipio_tjsp            645 non-null    str
 3   municipio_tjsp_corrigido  645 non-null    str
dtypes: int64(2), str(2)
memory usage: 20.3 KB

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido
0,3500105,6504,Adamantina,Adamantina
1,3500204,6505,Adolfo,Adolfo
2,3500303,6506,Aguaí,Aguaí
3,3500402,6507,Águas da Prata,Águas da Prata
4,3500501,6508,Águas de Lindóia,Águas de Lindóia

In [15]:
municipio.detalhe_batch()

# Results
municipio.df_detalhes.info()
municipio.df_detalhes.head()

<class 'pandas.DataFrame'>
Index: 1306 entries, 0 to 1309
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_municipio_tjsp  1306 non-null   int64
 1   raj                1306 non-null   str
 2   municipio_tjsp     1306 non-null   str
 3   comarca_tjsp       1306 non-null   str
 4   comarca_sede       1306 non-null   int64
 5   imovel             1306 non-null   str
dtypes: int64(2), str(4)
memory usage: 71.4 KB

,id_municipio_tjsp,raj,municipio_tjsp,comarca_tjsp,comarca_sede,imovel
0,6516,2ª RAJ Araçatuba,Alto Alegre,Penápolis,0,Fórum Penápolis I -
1,6516,2ª RAJ Araçatuba,Alto Alegre,Penápolis,0,Fórum Penápolis II - (Juizado Especial)
2,6514,8ª RAJ São José do Rio Preto,Altair,Olímpia,0,Fórum Olímpia I - (Principal)
3,6514,8ª RAJ São José do Rio Preto,Altair,Olímpia,0,Fórum Olímpia II (3ª Vara Cível)
4,6514,8ª RAJ São José do Rio Preto,Altair,Olímpia,0,Fórum Olímpia III - (Vara do Juizado Especial ...

<br>

---

### Imóveis

In [16]:
imovel = extract.Imovel(municipio=municipio)

In [17]:
imovel.search(termo='forum')

   id_imovel                                        imovel_tjsp
3          3                             Fórum Águas de Lindóia
5          4                                       Fórum Agudos
6          5                                  Fórum Altinópolis
7          6                                    Fórum Americana
9          7                          Fórum Américo Brasiliense
1        172      Fórum "Juiz Eleutério Dutra Filho" - Mongaguá
2        245  Fórum "Juiz Messias José de Melo Souza" (Sales...
4        415      Fórum Águas de Lindóia (J.E.CÍVEL e Criminal)
0        435         ANEXO FISCAL - Fórum Santa Bárbara d´Oeste
8        631                  Fórum Americana (CEJUSC) - UNISAL

In [19]:
imovel.search_batch()
imovel.df_search.head(50)

São 3192 termos para pesquisa

    id_imovel                                        imovel_tjsp
0           1                                 Fórum I Adamantina
1           2                                     Fórum de Aguaí
2           3                             Fórum Águas de Lindóia
3           4                                       Fórum Agudos
4           5                                  Fórum Altinópolis
5           6                                    Fórum Americana
6           7                          Fórum Américo Brasiliense
7           8  Prédio I - Fórum Dr. Laudo Ferreira de Camargo...
8           9         Fórum Andradina I (Homero Rodrigues Silva)
9          10                                   Fórum I Angatuba
10         11                                    Fórum Aparecida
11         12                      Fórum Araçatuba I - PRINCIPAL
12         13                                 Fórum Araraquara I
13         14  Fórum Araras - (Des.Manoel Carlos  da Costa Le...
14         15                                      Fórum Arujá I
15         16  Fórum Assis I - Dr. José Claudino de Oliveira ...
16         17                                    Fórum Atibaia I
17         18  Fórum Auriflama - (Ministro Domingos Franciull...
18         19                                    Fórum Avaré - I
19         21                                     Fórum Bariri I
20         22                               Fórum I Barra Bonita
21         23                                   Fórum I Barretos
22         25                                    Fórum de Bastos
23         26                                     Fórum Batatais
24         27                        Fórum Bauru I - (Principal)
25         28     Fórum Bebedouro - Desembargador Adriano Marrey
26         29                       FORUM DA COMARCA DE BERTIOGA
27         30  Fórum da Comarca de Bilac - (Coriolano Pompeu ...
28         31                                    Fórum I Birigüi
29         32               Fórum Boituva I  (Ofícios Judiciais)
30         33                                  Fórum Borborema I
31         35  Fórum Bragança Paulista - Professor Waldemar M...
32         36                                  Fórum I Brodowski
33         37  Fórum Brotas - Desembargador Júlio D´Elboux Gu...
34         38                                     Fórum Buritama
35         40            FORUM DE CAÇAPAVA PREDIO PRAÇA BANDEIRA
36         42   Fórum Caconde I - (Dr. Antônio de Queiroz Filho)
37         43                   Fórum Cafelândia I - (Principal)
38         44                                Fórum de Caieiras I
39         45  Fórum I Cajamar - (Desembargador Marcos Noguei...
40         46                    Fórum Cajuru (Dr. Amaury Manço)
41         48  Foro Regional de Vila Mimosa - Campinas (Des. ...
42         49                      Fórum de Campo Limpo Paulista
43         50  Fórum Campos do Jordão I - (Des.José Carlos de...
44         51         Fórum Cananéia - JOAQUIM GUEDES ALCOFORADO
45         52                                 Fórum Cândido Mota
46         53                                     Fórum Capivari
47         54                  Fórum da Comarca de Caraguatatuba
48         55  Fórum Carapicuíba I - (Des. Coaracy Lacerda Ma...
49         56                                      Fórum Cardoso

In [ ]:
df_unidades = listar_unidades.get_unidades_batch(
    list_id_tjsp=list(df_municipios["id_municipio_tjsp"]),
)

df_unidades.head()

<br>

---

## Tratamento

In [20]:
# Merge
df_unidades_merge = pd.merge(
    left=municipio.df_search,
    right=municipio.df_detalhes,
    left_on="id_municipio_tjsp",
    right_on="id_municipio_tjsp",
    how="inner",
    suffixes=["", "_copy"],
)

df_unidades_merge = df_unidades_merge.drop(
    labels=["municipio_tjsp_copy"],
    axis="columns",
    errors="ignore",
)

# Unidades
df_unidades_merge.info()
df_unidades_merge.head()

<class 'pandas.DataFrame'>
RangeIndex: 1306 entries, 0 to 1305
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_municipio_ibge         1306 non-null   int64
 1   id_municipio_tjsp         1306 non-null   int64
 2   municipio_tjsp            1306 non-null   str
 3   municipio_tjsp_corrigido  1306 non-null   str
 4   raj                       1306 non-null   str
 5   comarca_tjsp              1306 non-null   str
 6   comarca_sede              1306 non-null   int64
 7   imovel                    1306 non-null   str
dtypes: int64(3), str(5)
memory usage: 81.8 KB

,id_municipio_ibge,id_municipio_tjsp,municipio_tjsp,municipio_tjsp_corrigido,raj,comarca_tjsp,comarca_sede,imovel
0,3500105,6504,Adamantina,Adamantina,5ª RAJ Presidente Prudente,Adamantina,1,Fórum I Adamantina
1,3500105,6504,Adamantina,Adamantina,5ª RAJ Presidente Prudente,Adamantina,1,Fórum II Adamantina (Residência Oficial)
2,3500105,6504,Adamantina,Adamantina,5ª RAJ Presidente Prudente,Adamantina,1,Fórum III Adamantina - UAAJ - FAC. ADAM. INTEG...
3,3500204,6505,Adolfo,Adolfo,8ª RAJ São José do Rio Preto,José Bonifácio,0,Fórum José Bonifácio - II (CEJUSC)
4,3500204,6505,Adolfo,Adolfo,8ª RAJ São José do Rio Preto,José Bonifácio,0,Fórum José Bonifácio I (Principal)

<br>

---

### Comarcas

In [ ]:
df_tjsp = df_unidades_merge.copy()

# Comarca
df_tjsp_com = df_tjsp[df_tjsp["comarca_sede"] == 1]

# Filtra Colunas
df_tjsp_com = df_tjsp_com.drop(
    labels=[
        "comarca_sede",
        "unidades",
        "raj",
    ],
    axis="columns",
    errors="ignore",
)

# Deleta Duplicados
df_tjsp_com = df_tjsp_com.drop_duplicates()

# Renomeia Colunas
df_tjsp_com = df_tjsp_com.rename(
    {
        "municipio_tjsp_corrigido": "comarca_tjsp_corrigido",
        "id_municipio_ibge": "id_comarca",
    },
    axis="columns",
)

# Deleta
df_tjsp_com = df_tjsp_com.drop(
    labels=["municipio_tjsp"],
    axis="columns",
    errors="ignore",
)

# Bata Bater
df_tjsp_com = adjust_columns(
    df=df_tjsp_com,
    column_ajust="comarca_tjsp",
)

df_tjsp_com.info()
df_tjsp_com.head()

In [ ]:
df_temp = adjust_columns(df=quem_somos.comarcas, column_ajust="comarca_tjsp")

Usando `left` eu dropo a Vila Mimosa!

In [ ]:
df_tjsp_com = pd.merge(
    left=df_tjsp_com,
    right=df_temp,
    left_on="comarca_tjsp_temp",
    right_on="comarca_tjsp_temp",
    how="left",
    suffixes=["", "_copy"],
)

# Deleta
df_tjsp_com = df_tjsp_com.drop(
    labels=["comarca_tjsp_copy"],
    axis="columns",
    errors="ignore",
)

# Ordena
df_tjsp_com = df_tjsp_com.iloc[
    df_tjsp_com["comarca_tjsp"].str.normalize("NFKD").argsort()
]

# Reset Index
df_tjsp_com = df_tjsp_com.reset_index(drop=True)

df_tjsp_com = df_tjsp_com.drop(
    labels=["comarca_tjsp_temp", "id_municipio_tjsp"],
    axis="columns",
)

# Reordena
df_tjsp_com = df_tjsp_com[
    [
        "id_comarca",
        "comarca_tjsp",
        "comarca_tjsp_corrigido",
        "id_cj",
    ]
]

df_temp = df_tjsp_com[df_tjsp_com["id_cj"].isna()]
if len(df_temp) > 0:
    raise Exception("Erro")

df_tjsp_com.info()
df_tjsp_com.head()

<br>

---

### Municipios > Comarcas

In [ ]:
# Filtra Colunas
df_municipios_fim = df_unidades_merge.drop(
    labels=[
        "unidades",
        "raj",
        #'id_municipio_tjsp'
    ],
    axis="columns",
    errors="ignore",
)

# Deleta Duplicados
df_municipios_fim = df_municipios_fim.drop_duplicates()

# Reset Index
df_municipios_fim = df_municipios_fim.reset_index(drop=True)

df_municipios_fim.info()
df_municipios_fim.head()

In [ ]:
df_temp = adjust_columns(df=df_municipios_fim, column_ajust="comarca_tjsp")
df_temp.head()

In [ ]:
df_temp2 = adjust_columns(df=df_tjsp_com, column_ajust="comarca_tjsp")

# Filtra Colunas
df_temp2 = df_temp2.drop(
    labels=[
        "comarca_tjsp",
        "comarca_tjsp_corrigido",
        "id_cj",
    ],
    axis="columns",
    errors="ignore",
)

df_temp2.head()

In [ ]:
# Merge
df_temp3 = pd.merge(
    left=df_temp,
    right=df_temp2,
    left_on="comarca_tjsp_temp",
    right_on="comarca_tjsp_temp",
    how="left",
    suffixes=["", "_copy"],
)

# Filtra Colunas
df_temp3 = df_temp3.drop(
    labels=[
        "comarca_tjsp_temp",
        "comarca_tjsp",
    ],
    axis="columns",
    errors="ignore",
)

df_temp = df_temp3[df_temp3["id_comarca"].isna()]
if len(df_temp) > 0:
    raise Exception("Erro")

# Results
df_temp3.info()
df_temp3.head()

<br>

---

### Unidades

In [ ]:
# Unidades
df_unidades_merge.info()
df_unidades_merge.head()

In [ ]:
df_tjsp_unidades = df_unidades_merge[["id_municipio_ibge", "imoveis"]]
df_tjsp_unidades = df_tjsp_unidades.drop_duplicates()
df_tjsp_unidades